/**
*  @file gsiDeclQStyleOptionQ3ListViewItem.cc 
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#include <QStyleOptionQ3ListViewItem>
#include <QStyleOption>
#include <QWidget>
#include "gsiQt.h"
#include "gsiQtCommon.h"
#include "gsiDeclQtTypeTraits.h"
#include <memory>

// -----------------------------------------------------------------------
// class QStyleOptionQ3ListViewItem

//  Constructor QStyleOptionQ3ListViewItem::QStyleOptionQ3ListViewItem()


static void _init_ctor_QStyleOptionQ3ListViewItem_0 (qt_gsi::GenericStaticMethod *decl)
{
  decl->set_return_new<QStyleOptionQ3ListViewItem> ();
}

static void _call_ctor_QStyleOptionQ3ListViewItem_0 (const qt_gsi::GenericStaticMethod * /*decl*/, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  __SUPPRESS_UNUSED_WARNING(args);
  ret.write<QStyleOptionQ3ListViewItem *> (new QStyleOptionQ3ListViewItem ());
}


//  Constructor QStyleOptionQ3ListViewItem::QStyleOptionQ3ListViewItem(const QStyleOptionQ3ListViewItem &other)


static void _init_ctor_QStyleOptionQ3ListViewItem_3910 (qt_gsi::GenericStaticMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("other");
  decl->add_arg<const QStyleOptionQ3ListViewItem & > (argspec_0);
  decl->set_return_new<QStyleOptionQ3ListViewItem> ();
}

static void _call_ctor_QStyleOptionQ3ListViewItem_3910 (const qt_gsi::GenericStaticMethod * /*decl*/, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  __SUPPRESS_UNUSED_WARNING(args);
  tl::Heap heap;
  const QStyleOptionQ3ListViewItem &arg1 = args.read<const QStyleOptionQ3ListViewItem & > (heap);
  ret.write<QStyleOptionQ3ListViewItem *> (new QStyleOptionQ3ListViewItem (arg1));
}



namespace gsi
{

static gsi::Methods methods_QStyleOptionQ3ListViewItem () {
  gsi::Methods methods;
  methods += new qt_gsi::GenericStaticMethod ("new", "@brief Constructor QStyleOptionQ3ListViewItem::QStyleOptionQ3ListViewItem()\nThis method creates an object of class QStyleOptionQ3ListViewItem.", &_init_ctor_QStyleOptionQ3ListViewItem_0, &_call_ctor_QStyleOptionQ3ListViewItem_0);
  methods += new qt_gsi::GenericStaticMethod ("new", "@brief Constructor QStyleOptionQ3ListViewItem::QStyleOptionQ3ListViewItem(const QStyleOptionQ3ListViewItem &other)\nThis method creates an object of class QStyleOptionQ3ListViewItem.", &_init_ctor_QStyleOptionQ3ListViewItem_3910, &_call_ctor_QStyleOptionQ3ListViewItem_3910);
  return methods;
}

gsi::Class<QStyleOption> &qtdecl_QStyleOption ();

gsi::Class<QStyleOptionQ3ListViewItem> decl_QStyleOptionQ3ListViewItem (qtdecl_QStyleOption (), "QStyleOptionQ3ListViewItem",
  methods_QStyleOptionQ3ListViewItem (),
  "@qt\n@brief Binding of QStyleOptionQ3ListViewItem");


GSIQT_PUBLIC gsi::Class<QStyleOptionQ3ListViewItem> &qtdecl_QStyleOptionQ3ListViewItem () { return decl_QStyleOptionQ3ListViewItem; }

}

