/**
*  @file gsiDeclQStyleOptionSlider.cc 
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#include <QStyleOptionSlider>
#include <QStyleOption>
#include <QWidget>
#include "gsiQt.h"
#include "gsiQtCommon.h"
#include "gsiDeclQtTypeTraits.h"
#include <memory>

// -----------------------------------------------------------------------
// class QStyleOptionSlider

//  Constructor QStyleOptionSlider::QStyleOptionSlider()


static void _init_ctor_QStyleOptionSlider_0 (qt_gsi::GenericStaticMethod *decl)
{
  decl->set_return_new<QStyleOptionSlider> ();
}

static void _call_ctor_QStyleOptionSlider_0 (const qt_gsi::GenericStaticMethod * /*decl*/, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  __SUPPRESS_UNUSED_WARNING(args);
  ret.write<QStyleOptionSlider *> (new QStyleOptionSlider ());
}


//  Constructor QStyleOptionSlider::QStyleOptionSlider(const QStyleOptionSlider &other)


static void _init_ctor_QStyleOptionSlider_3167 (qt_gsi::GenericStaticMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("other");
  decl->add_arg<const QStyleOptionSlider & > (argspec_0);
  decl->set_return_new<QStyleOptionSlider> ();
}

static void _call_ctor_QStyleOptionSlider_3167 (const qt_gsi::GenericStaticMethod * /*decl*/, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  __SUPPRESS_UNUSED_WARNING(args);
  tl::Heap heap;
  const QStyleOptionSlider &arg1 = args.read<const QStyleOptionSlider & > (heap);
  ret.write<QStyleOptionSlider *> (new QStyleOptionSlider (arg1));
}



namespace gsi
{

static gsi::Methods methods_QStyleOptionSlider () {
  gsi::Methods methods;
  methods += new qt_gsi::GenericStaticMethod ("new", "@brief Constructor QStyleOptionSlider::QStyleOptionSlider()\nThis method creates an object of class QStyleOptionSlider.", &_init_ctor_QStyleOptionSlider_0, &_call_ctor_QStyleOptionSlider_0);
  methods += new qt_gsi::GenericStaticMethod ("new", "@brief Constructor QStyleOptionSlider::QStyleOptionSlider(const QStyleOptionSlider &other)\nThis method creates an object of class QStyleOptionSlider.", &_init_ctor_QStyleOptionSlider_3167, &_call_ctor_QStyleOptionSlider_3167);
  return methods;
}

gsi::Class<QStyleOptionComplex> &qtdecl_QStyleOptionComplex ();

gsi::Class<QStyleOptionSlider> decl_QStyleOptionSlider (qtdecl_QStyleOptionComplex (), "QStyleOptionSlider",
  methods_QStyleOptionSlider (),
  "@qt\n@brief Binding of QStyleOptionSlider");


GSIQT_PUBLIC gsi::Class<QStyleOptionSlider> &qtdecl_QStyleOptionSlider () { return decl_QStyleOptionSlider; }

}

