#include <QtCore5Compat/QBinaryJson>
#include <QtCore5Compat/QConcatenable>
#include <QtCore5Compat/QLinkedList>
#include <QtCore5Compat/QLinkedListData>
#include <QtCore5Compat/QLinkedListIterator>
#include <QtCore5Compat/QLinkedListNode>
#include <QtCore5Compat/QMutableLinkedListIterator>
#include <QtCore5Compat/QRegExp>
#include <QtCore5Compat/QStringRef>
//#include <QtCore5Compat/QtCore5Compat>
//#include <QtCore5Compat/QtCore5CompatDepends>
#include <QtCore5Compat/QtCore5CompatVersion>
#include <QtCore5Compat/QTextCodec>
#include <QtCore5Compat/QTextDecoder>
#include <QtCore5Compat/QTextEncoder>
#include <QtCore5Compat/QXmlAttributes>
#include <QtCore5Compat/QXmlContentHandler>
#include <QtCore5Compat/QXmlDeclHandler>
#include <QtCore5Compat/QXmlDefaultHandler>
#include <QtCore5Compat/QXmlDTDHandler>
#include <QtCore5Compat/QXmlEntityResolver>
#include <QtCore5Compat/QXmlErrorHandler>
#include <QtCore5Compat/QXmlInputSource>
#include <QtCore5Compat/QXmlLexicalHandler>
#include <QtCore5Compat/QXmlLocator>
#include <QtCore5Compat/QXmlNamespaceSupport>
#include <QtCore5Compat/QXmlParseException>
#include <QtCore5Compat/QXmlReader>
#include <QtCore5Compat/QXmlSimpleReader>
