#include "QtSvg/QGraphicsSvgItem"
#include "QtSvg/QSvgGenerator"
#include "QtSvg/QSvgRenderer"
#include "QtSvg/QSvgWidget"
#include "QtSvg/QtSvg"
#include "QtSvg/QtSvgDepends"
#include "QtSvg/QtSvgVersion"
