---
name: Upload Mac Python Wheel to PyPI

on:
  release:
    types: [created, published]
  push:
    branches: [master]
    tags: [v*]
  workflow_dispatch:

jobs:
  mac-deploy:
    needs: [mac-build, build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-11", "macos-10.15"]
        python-version: [3.7, 3.8, 3.9, '3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.python-version }}-${{ matrix.os }}  # Make cache specific to OS
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build the macOS wheels
        run: |
          pip3 install twine
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          pip3 install -e . --no-index
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload dist/*
