---
name: Upload Mac Python Wheel to PyPI

on:
  release:
    types: [created, published]
  push:
    branches: [master]
    tags: [v*]
  workflow_dispatch:

jobs:
  mac-build:
    name: Wrapper macOS Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-11", "macos-10.15"]
        pyversion: ["python@3.8", "python@3.9", "python@3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}  # Make cache specific to OS
      - name: Build the macOS wheels
        run: |
          pip3 install twine
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ccache -s
          pip3 install -e . --no-index
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 setup.py sdist bdist_wheel
          ccache -s
          twine upload dist/*
