---
name: Mac test python package

on:
  pull_request:
  push:

jobs:
  mac-build:
    name: Wrapper macOS Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-11", "macos-10.15"]
        pyversion: ["python@3.8", "python@3.9", "python@3.10"]
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout
        uses: actions/checkout@master
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}  # Make cache specific to OS
      - name: Build the macOS wheels
        run: |
          pip3 install twine
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ccache -s
          pip3 install -e . --no-index
          ccache -s
      - name: Test code
        run: |
          python3 testdata/pymod/import_db.py
          python3 testdata/pymod/import_rdb.py
          python3 testdata/pymod/import_tl.py
          python3 testdata/pymod/import_lib.py
          python3 testdata/pymod/pya_tests.py
